public enum BeLordCommand
{
	LOGIN = 0,
	REPORT_ACHIEVEMENT = 1,
	RESET_ACHIEVEMENTS = 2,
	LOAD_ACHIEVEMENTS = 3,
	LOAD_ACHIEVEMENTS_MD = 4,
	LOAD_LEADERBOARDS_CATS = 5,
	REPORT_SCORE = 6,
	LOAD_SCORES = 7
}
