public enum LevelTileChunk
{
	UNKNOWN = -1,
	PLANE = 0,
	START_RAMP = 1,
	HALF_ELEVATED = 2,
	NARROW_PLANE_MIDDLE = 3,
	NARROW_PLANE_SIDE = 4,
	START_NARROWER = 5,
	START_NARROW_TUNNEL = 6,
	NARROW_TUNNEL_1 = 7,
	NARROW_TUNNEL_2 = 8,
	START_BRIDGE = 9,
	BRIDGE_1 = 10,
	BRIDGE_2 = 11,
	BRIDGE_BROKEN = 12,
	STAIRS = 13
}
