public enum SndIdMenu
{
	SND_MENU_MUSIC_INTRO = 0,
	SND_MENU_MUSIC_LOOP = 1,
	SND_MENU_CLICK = 2,
	SND_MENU_COLLAPSE_MENU = 3,
	SND_MENU_EXPAND_MENU = 4,
	SND_MENU_GAME_START = 5,
	SND_MENU_SLIDE_LEFT = 6,
	SND_MENU_SLIDE_RIGHT = 7,
	SND_MENU_PURCHASE = 8,
	SND_MENU_DING = 9
}
